### ISSUE TITLE
Document comma issue with @Bean

### ISSUE THREAD

**Issue by GoogleCodeExporter** [brunoais/javadude#26]
```
[exec] An exception has occurred in apt (1.6.0_02). Please file a bug at 
the Java Developer Connection (http://java.sun.com/webapps/bugreport) 
after checking the Bug Parade for duplicates. Include your program and the 
following diagnostic in your report.  Thank you.
     [exec] java.lang.ClassCastException: 
com.sun.tools.javac.tree.JCTree$JCErroneous cannot be cast to 
com.sun.tools.javac.tree.JCTree$JCAnnotation
     [exec]     at com.sun.tools.javac.comp.Annotate.enterAttributeValue
(Annotate.java:205)
     [exec]     at com.sun.tools.javac.comp.Annotate.enterAttributeValue
(Annotate.java:219)
     [exec]     at com.sun.tools.javac.comp.Annotate.enterAnnotation
(Annotate.java:167)
     [exec]     at com.sun.tools.javac.comp.MemberEnter.enterAnnotations
(MemberEnter.java:743)
     [exec]     at com.sun.tools.javac.comp.MemberEnter.access$300
(MemberEnter.java:42)
     [exec]     at com.sun.tools.javac.comp.MemberEnter$5.enterAnnotation
(MemberEnter.java:711)
     [exec]     at com.sun.tools.javac.comp.Annotate.flush
(Annotate.java:95)
     [exec]     at com.sun.tools.javac.comp.Annotate.enterDone
(Annotate.java:87)

     [exec]     at com.sun.tools.javac.comp.Enter.complete(Enter.java:472)
     [exec]     at com.sun.tools.javac.comp.Enter.main(Enter.java:429)
     [exec]     at com.sun.tools.apt.main.JavaCompiler.compile
(JavaCompiler.java:250)
     [exec]     at com.sun.tools.apt.main.Main.compile(Main.java:1102)
     [exec]     at com.sun.tools.apt.main.Main.compile(Main.java:964)
     [exec]     at com.sun.tools.apt.Main.processing(Main.java:95)
     [exec]     at com.sun.tools.apt.Main.process(Main.java:43)
     [exec]     at com.sun.tools.apt.Main.main(Main.java:34)


```

Original issue reported on code.google.com by `scott%ja...@gtempaccount.com` on 3 Nov 2008 at 5:01

**Comment by GoogleCodeExporter** [comment]
Original comment by `scott%ja...@gtempaccount.com` on 3 Nov 2008 at 5:02
- Added labels: **Project-Annotations**

**Comment by GoogleCodeExporter** [comment]
Original comment by `scott%ja...@gtempaccount.com` on 3 Nov 2008 at 5:03
- Added labels: **Priority-Medium**
