### ISSUE TITLE
ClassCastException in BeanAnnotationProcessor.processProperties

### ISSUE THREAD

**Issue by GoogleCodeExporter** [brunoais/javadude#54]
```
I get a ClassCastException with the annotation processor from revision r400.

Unexpected exception: java.lang.ClassCastException:
com.sun.tools.apt.mirror.type.ClassTypeImpl cannot be cast to
com.sun.mirror.type.PrimitiveType
[WARNING]   at
com.javadude.annotation.processors.BeanAnnotationProcessor.processProperties(Bea
nAnnotationProcessor.java:559)
[WARNING]   at
com.javadude.annotation.processors.BeanAnnotationProcessor.process(BeanAnnotatio
nProcessor.java:281)
[WARNING]   at
com.sun.mirror.apt.AnnotationProcessors$CompositeAnnotationProcessor.process(Ann
otationProcessors.java:60)
[WARNING]   at com.sun.tools.apt.comp.Apt.main(Unknown Source)
[WARNING]   at com.sun.tools.apt.main.JavaCompiler.compile(Unknown Source)
[WARNING]   at com.sun.tools.apt.main.Main.compile(Unknown Source)
[WARNING]   at com.sun.tools.apt.main.Main.compile(Unknown Source)
[WARNING]   at com.sun.tools.apt.Main.processing(Unknown Source)
[WARNING]   at com.sun.tools.apt.Main.process(Unknown Source)
[WARNING]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[WARNING]   at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[WARNING]   at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
[WARNING]   at java.lang.reflect.Method.invoke(Method.java:597)
[WARNING]   at org.codehaus.mojo.apt.AptUtils.invoke(AptUtils.java:114)
[WARNING]   at
org.codehaus.mojo.apt.AbstractAptMojo.executeApt(AbstractAptMojo.java:373)
[WARNING]   at
org.codehaus.mojo.apt.AbstractAptMojo.executeImpl(AbstractAptMojo.java:263)
[WARNING]   at
org.codehaus.mojo.apt.AbstractAptMojo.execute(AbstractAptMojo.java:240)
[WARNING]   at
org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.ja
va:490)
[WARNING]   at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycl
eExecutor.java:694)
[WARNING]   at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(Def
aultLifecycleExecutor.java:556)
[WARNING]   at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycle
Executor.java:535)
[WARNING]   at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures
(DefaultLifecycleExecutor.java:387)
[WARNING]   at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultL
ifecycleExecutor.java:348)
[WARNING]   at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExec
utor.java:180)
[WARNING]   at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
[WARNING]   at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
[WARNING]   at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
[WARNING]   at
org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
[WARNING]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[WARNING]   at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[WARNING]   at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
[WARNING]   at java.lang.reflect.Method.invoke(Method.java:597)
[WARNING]   at
org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
[WARNING]   at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
[WARNING]   at
org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
[WARNING]   at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

```

Original issue reported on code.google.com by `tisoftmedia` on 13 Apr 2010 at 2:25

**Comment by GoogleCodeExporter** [comment]
```
The latest code isn't cooked yet. I'm only supporting the one that can be 
obtained 
through the update site. The version in trunk took a very new direction and I 
haven't 
had time to test.
```

Original comment by `scott%ja...@gtempaccount.com` on 13 Apr 2010 at 2:30
- Changed state: **Invalid**
